### ISSUE TITLE
connection close

### ISSUE THREAD

**Issue by diazzaid** [ade566/wa-baileys#1]
hallo bro
apakah isu ini sudah solve ?
https://github.com/adiwajshing/Baileys/issues/1218
sy cek antara 5 menit sekali selalu close

**Comment by ade566** [comment]
Di issue https://github.com/adiwajshing/Baileys/issues/1218 saya belum dapet solvenya, tapi saya coba dengan script yang sekarang berjalan normal walau saya pake berjam jam, terjadi *connection close* ketika kirim pesan saat koneksi tidak stabil

**Comment by diazzaid** [comment]
> Di issue [adiwajshing/Baileys#1218](https://github.com/adiwajshing/Baileys/issues/1218) saya belum dapet solvenya, tapi saya coba dengan script yang sekarang berjalan normal walau saya pake berjam jam, terjadi _connection close_ ketika kirim pesan saat koneksi tidak stabil

Ok mas nuhun
